// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjpstE7xEdPTm6WjHw6cU3_CwJdHU4BcA',
    appId: '1:844779781107:web:72448c970dd802fce3f086',
    messagingSenderId: '844779781107',
    projectId: 'service-pro-ci',
    authDomain: 'service-pro-ci.firebaseapp.com',
    storageBucket: 'service-pro-ci.firebasestorage.app',
    measurementId: 'G-FDN0NLP6ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxTyW5Hd2WWORvRLAxRw4UdSbjhxO_f2A',
    appId: '1:844779781107:android:05148f9b8ae4b9f4e3f086',
    messagingSenderId: '844779781107',
    projectId: 'service-pro-ci',
    storageBucket: 'service-pro-ci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5jxyG3pSdxCyAOJGWaxl-SSwlMOd4do',
    appId: '1:844779781107:ios:bb0af44746691033e3f086',
    messagingSenderId: '844779781107',
    projectId: 'service-pro-ci',
    storageBucket: 'service-pro-ci.firebasestorage.app',
    iosBundleId: 'com.example.serviceProCi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5jxyG3pSdxCyAOJGWaxl-SSwlMOd4do',
    appId: '1:844779781107:ios:bb0af44746691033e3f086',
    messagingSenderId: '844779781107',
    projectId: 'service-pro-ci',
    storageBucket: 'service-pro-ci.firebasestorage.app',
    iosBundleId: 'com.example.serviceProCi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjpstE7xEdPTm6WjHw6cU3_CwJdHU4BcA',
    appId: '1:844779781107:web:82b2f6591948e7ace3f086',
    messagingSenderId: '844779781107',
    projectId: 'service-pro-ci',
    authDomain: 'service-pro-ci.firebaseapp.com',
    storageBucket: 'service-pro-ci.firebasestorage.app',
    measurementId: 'G-85TNHHRJPE',
  );
}
